[package]
name = "vaultai"
version = "0.1.0"
description = "VaultAI is the ultimate self-contained AI chatbot: enjoy uncensored, unlimited use with no token limits, zero AI watermarks, and 100% personalized responses"
authors = ["ikram98ai"]
edition = "2024"

[profile.dev]
debug = 0
strip = "debuginfo"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[lib]
name = "vaultai_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = "1.0.100"
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = "1"
sysinfo = "0.37.2"
tauri = { version = "2", features = [] }
tauri-plugin-fs = "2"
tauri-plugin-opener = "2"
tauri-plugin-sql = { version = "2", features = ["sqlite"] }
tauri-plugin-shell = "2"
tokio = { version = "1", features = ["rt-multi-thread", "fs", "net"]  }
reqwest = { version = "0.13.2", features = ["json"] }

