[package]
name = "vaultai"
version = "0.1.0"
description = "VaultAI is the ultimate self-contained AI chatbot: enjoy uncensored, unlimited use with no token limits, zero AI watermarks, and 100% personalized responses"
authors = ["ikram98ai"]
edition = "2024"

[lib]
name = "vaultai_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-sql = "2"

